### ISSUE TITLE
Player respawns and spectates simultaneously when killed at tickets = 0 in multiplayer game

### ISSUE THREAD

**Issue by BriscoeTech** [Ansible2/Arma-3-Survival#451]
Hello Ansible2,

We have noticed an interesting respawn loophole that happens when there are no tickets left in a wave.

In multiplayer games if a player is killed and tickets = 0, their player still respawns and is controllable by "W" "A" "S" "D" movement, and downed hold space for respawn ui option still exists. What is strange is the spectating mode UI is now also visible, and the players mouse movement is disabled, making the player both alive/ downed /and in spectate mode simultaneously. If the player is killed/clicks esc menu respawn/hold space to respawn/ then the player fully enters spectate mode and there is no longer a movable player model.

**Comment by Ansible2** [comment]
Closed in #581
