### ISSUE TITLE
Respawn UI different text if you do/dont have a medkit present

### ISSUE THREAD

**Issue by BriscoeTech** [Ansible2/Arma-3-Survival#452]
Based on a comment in a different thread, I went back in and realized that now you have to hold space to force respawn, and if you have a medkit you get back up. This is a nice option to not always waste a medkit when someone is nearby.

How difficult is it to have the ui for respawn be different depending on if you do/dont have a medkit? If you have a medkit, it could say "hold space to medkit revive" vs "hold space to respawn"

**Comment by Ansible2** [comment]
The text is supposed to be there, but something with the way either hold actions are or specifically the force respawn action added by the revive cause some issues with the text showing up.

#455
