### ISSUE TITLE
Parameters not saving

### ISSUE THREAD

**Issue by 0xlord** [Ansible2/Arma-3-Survival#454]
Hello,

we are using the "nightly build" from 20210412-2100UTC+2 from github (aka download of any files, then exporting as pbo).
We are not able to save the parameters for after a server reboot. I do it like this:

 * Starting the server
 * Logging into it
 * Logging into admin state with `#login`
 * Doing `#missions` to reload the mission to edit the parameters in the lobby
 * Editing the parameters 
 * Starting into the match/game
 * Entering the map and saving the parameters 
 * Restarting the map/server (both does not work)
 * Parameters are back on vanilla state

Am I doing something wrong? Or is this indeed a bug? 

Thanks for any help :-)

**Comment by Ansible2** [comment]
If you haven't already, try resetting the saved parameters and then saving again.

- Is this a rented server from a service?
- Do you get a hint notification that the parameters have been saved?

After you've saved run this in the debug console and **execute on the server** to verify that the contents are saved:
```
profileNamespace getVariable "BLWK_savedMissionParameters";
```

Given that the settings are saved to the `profileNamespace`, depending on your setup it could be that the server profile is just simply not the same. To see if this is the case try saving random entry to the `profileNamespace` while in the server:



1. Save the test variable on the server (Execute on the server)
```
profileNamespace setVariable ["myTestVar",1];
saveProfileNamespace;
```

2. Perform a restart of the server

3. Check if the parameter saved: (Execute on the server)

```
profileNamespace getVariable ["myTestVar",0];
```

4. A return of `1` means it was saved `0` means it did not.

**Comment by 0xlord** [comment]
Hello,

I've got a `1` return as intended. I also got a huge list of stuff when I ask for the savedMissionParameters. Additionally I've seen that most of the settings got saved. But the fractions are always getting reseted to the vanilla ones. Just tried it out again (setting up each wave to a Project OPFOR or RHS AFRF fraction and the own units to a USAF force), started the missions, got the respective units, restarted the server and got the standard vanilla options as parameters again. 
Every other option works so far.

Thanks for your help. Here the saved parameters so far - saved after I've loaded the RHS/OPFOR fractions and before the server restart:

```[["BLWK_maxEnemyInfantryAtOnce",30],["BLWK_timeOfDay",6],["ReviveDuration",8],["ReviveBleedOutDuration",120],["BLWK_friendlyFaction",198],["BLWK_multipleLootReveals",1],["BLWK_faksToMakeMedkit",10],["BLWK_staminaEnabled",0],["BLWK_startingWaveNumber",0],["ReviveMedicSpeedMultiplier",1],["BLWK_heavyCarLikelihood",5],["BLWK_weaponSwayCoef",15],["BLWK_startingKillPoints",0],["BLWK_playersStartWith_pistol",0],["ReviveForceRespawnDuration",-100],["BLWK_doDetectCollision",1],["BLWK_suppressionEnabled",0],["BLWK_roundsBeforeBodyDeletion",1],["BLWK_minRoundsSinceVehicleSpawned",0],["BLWK_friendlyFireOn",1],["UnconsciousStateMode",-100],["BLWK_maxNumWaves",25],["BLWK_specialWavesStartAt",7],["BLWK_enemiesPerWaveMultiplier",10],["BLWK_playersStartWith_NVGs",0],["ReviveRequiredItems",2],["BLWK_startingCommunityKillPoints",0],["BLWK_level3Faction",163],["BLWK_baseVehicleSpawnLikelihood",6],["BLWK_deleteDroppedItemsEvery",3],["BLWK_maxPistolOnlyWaves",3],["BLWK_playersStartWith_compass",1],["BLWK_minNumberOfHousesInArea",15],["BLWK_loot_cityDistribution",1],["BLWK_loot_whiteListMode",0],["BLWK_daySpeedMultiplier",6],["BLWK_level1Faction",166],["BLWK_vehicleStartWave",5],["BLWK_playersStartWith_radio",1],["BLWK_buildingsNearTheCrateAreIndestructable_radius",20],["ReviveMode",1],["BLWK_lightArmorLikelihood",5],["BLWK_doDetectMines",1],["BLWK_aircraftGunnerLifetime",2],["BLWK_numMedKits",3],["BLWK_customPlayLocation",0],["BLWK_showHitPoints",1],["BLWK_pointsMultiForDamage",20],["BLWK_level4Faction",185],["BLWK_timeBetweenRounds",60],["BLWK_heavyArmorLikelihood",4],["BLWK_autocombatEnabled",0],["BLWK_fallDamageOn",0],["BLWK_playersStartWith_map",1],["BLWK_playersStartWith_mineDetector",1],["BLWK_saveRespawnLoadout",0],["BLWK_pointsForKill",125],["BLWK_level5Faction",181],["BLWK_supportDishFound",1],["BLWK_level2Faction",170],["BLWK_randomizeEnemyWeapons",0],["BLWK_enemiesPerPlayerMultiplier",10],["BLWK_playAreaRadius",100],["BLWK_loot_roomDistribution",2],["Weather",25],["BLWK_numRespawnTickets",10],["BLWK_lightCarLikelihood",4],["BLWK_pointsForHit",30],["ReviveRequiredTrait",0],["BLWK_magRepackEnabled",1]]```

Edit: The factions are non standard now in the settings above. I've put them as standard parameters into the mission. That's why they differ from the vanilla settings now.

**Comment by Ansible2** [comment]
Factions are not saved by default (I haven't made this clear anywhere that I can recall tbh). 

This is because the faction list is currently index based (this is mostly because of limitations with Arma 3's Mission Parameter framework) which means that if a faction is added or removed it has the potential of altering what faction would be at someone's saved index.

I'm thinking about changing it to be loaded, but, what you can do is in the `MissionParams.hpp` is just edit the default faction (number) to what you currently have in the save output. 

You can also just replace the entire faction section in it with the following to load your saved param:
```cpp
A_SPACE(Faction);
A_SECTION_HEADER(Faction);
class BLWK_friendlyFaction
{
	title = "Friendly Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_friendlyFaction,0)
};

class BLWK_level1Faction
{
	title = "Level 1 Enemy Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_level1Faction,2)
};

class BLWK_level2Faction
{
	title = "Level 2 Enemy Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_level2Faction,1)
};

class BLWK_level3Faction
{
	title = "Level 3 Enemy Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_level3Faction,3)
};

class BLWK_level4Faction
{
	title = "Level 4 Enemy Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_level4Faction,4)
};

class BLWK_level5Faction
{
	title = "Level 5 Enemy Faction";
	values[] = {FACTION_COUNT};
	texts[] = {FACTION_STRINGS};
	GET_DEFAULT_PARAM(BLWK_level5Faction,13)
};
```
https://github.com/Ansible2/Arma-3-Survival/blob/3a23723248064054528eab8dfe9d12526512b9d4/Headers/descriptionEXT/missionParams.hpp

**Comment by 0xlord** [comment]
Hi Ansible2,

I've updated the missionParams as you've suggested and it works like intended. Thank you very much. Would be good to have the factions being saved as well, but I can live with this. 

I close the ticket for now.
