### ISSUE TITLE
Stagger the body deletion counter for every 5 or so waves

### ISSUE THREAD

**Issue by 0xlord** [Ansible2/Arma-3-Survival#474]
We finally managed to get through all 25 waves yesterday. Starting around Wave 12 - 15 performance decreased dramatically due to the very high amount of bodies on the ground. Could you make the parameter on how many waves bodies gets deleted staggering for ever 5 or so waves, please?

For example: 
 * Till wave 5
 * Till wave 10
 * Till wave 15
 * Till wave 20
 * Till wave 25

Or, to make it easier 
 * From the start
 * From wave 10
 * From wave 20

I think most wouldn't set from wave 20 to anything above 1 anyways.

**Comment by aussie-battler** [comment]
You can just delete  bodies every round & extend the loot timer between rounds.

https://github.com/Ansible2/Arma-3-Survival/blob/312d4a5782454f98b77bfbdc39fca83895e4b45b/Headers/descriptionEXT/missionParams.hpp#L119

https://github.com/Ansible2/Arma-3-Survival/blob/312d4a5782454f98b77bfbdc39fca83895e4b45b/Headers/descriptionEXT/missionParams.hpp#L62

**Comment by 0xlord** [comment]
The server is running publicly. I am not always on to delete the bodies. I want this for the players so they have a better performance experience. Also I've already set the parameter to delete bodies after one round. But thank you nevertheless.

**Comment by aussie-battler** [comment]
I have bodies deleting every round & it is working for me. I had to change the player distance to 10m for dead body removal. 

1. I have this set to 0:
https://github.com/Ansible2/Arma-3-Survival/blob/312d4a5782454f98b77bfbdc39fca83895e4b45b/Headers/descriptionEXT/missionParams.hpp#L124 

2. I have player distance to delete dead body at 10m:
https://github.com/Ansible2/Arma-3-Survival/blob/312d4a5782454f98b77bfbdc39fca83895e4b45b/description.ext#L32

**Comment by 0xlord** [comment]
Thanks @aussie-battler, this works fine for me as well. Closing the ticket.
