### ISSUE TITLE
Box heal broken

### ISSUE THREAD

**Issue by TheMagicalKing** [Ansible2/Arma-3-Survival#517]
unsure if this relates to issue #271 due to ACE being present on the server or not. if so, how to change so it works?

**Comment by mtp** [comment]
I confirm, if using ACE, the box heal is not working. I guess it would have to detect if the server is using ace or not, and if so it would heal the player using ace system.

**Comment by Ansible2** [comment]
What was the `Revive Mode` mission parameter set to? Needs to be "Disabled" if ACE is present.

**Comment by TheMagicalKing** [comment]
revive mode was set to 1, sorry for the mistake! :)

@mtp check the ReviveParams.hpp
