### ISSUE TITLE
Wave Issue  -  Spawn before timer

### ISSUE THREAD

**Issue by psvialli** [Ansible2/Arma-3-Survival#586]
The wave starts before the timer ends  men appear and shoot before / during the countdown.

* Have worked it out if i play in MP on my PC it all works as it should but as soon as I put it on my Dedi server it spawn during countdown and after each Wave it stats a new wave without any delay so it is a Dedi Issue 
-  also is there no way to set a duration between waves ?

**Comment by Ansible2** [comment]
You change it in the Mission Parameter Menu -> `Waves` (category) -> `Time between rounds` setting.

**Comment by psvialli** [comment]
OK my Bad all working after Update  MANY THANKS !!!!!!!!!!!!!!!!!!!!!

Dedi now working
